"""initial; extend num

Revision ID: 9f679106948d
Revises: 
Create Date: 2026-02-17 22:23:02.344381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f679106948d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'node_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('CITY', 'VILLAGE', 'AIRPORT', 'TRAIN_STATION', 'BUS_STATION', 'BUS_STOP', 'TRANSPORT_STOP', name='nodetype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'node_type',
               existing_type=sa.Enum('CITY', 'VILLAGE', 'AIRPORT', 'TRAIN_STATION', 'BUS_STATION', 'BUS_STOP', 'TRANSPORT_STOP', name='nodetype', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
