"""add metrics to point_node

Revision ID: cd2589563199
Revises: 9f679106948d
Create Date: 2026-03-19 11:43:25.578220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2589563199'
down_revision: Union[str, Sequence[str], None] = '9f679106948d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first to avoid IntegrityError with existing data
    op.add_column('point_nodes', sa.Column('comfort_score', sa.Float(), nullable=True))
    op.add_column('point_nodes', sa.Column('co2_kg', sa.Float(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE point_nodes SET comfort_score = 5.0 WHERE comfort_score IS NULL")
    op.execute("UPDATE point_nodes SET co2_kg = 0.0 WHERE co2_kg IS NULL")
    
    # Now set them to NOT NULL
    op.alter_column('point_nodes', 'comfort_score', nullable=False)
    op.alter_column('point_nodes', 'co2_kg', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_nodes', 'co2_kg')
    op.drop_column('point_nodes', 'comfort_score')
    # ### end Alembic commands ###
